export enum AppEvent {
    BOOKING_CREATED = 'BOOKING_CREATED',
    FREE_BOOKING_CREATED = 'FREE_BOOKING_CREATED',
    APP_NOTIFICATION = 'APP_NOTIFICATION',
    APP_BATCH_NOTIFICATIONS = 'APP_BATCH_NOTIFICATIONS',
    INSTALLMENT_REMINDER = 'INSTALLMENT_REMINDER',
    BILLING_PROCESS_EVENT = 'BILLING_PROCESS_EVENT',
    DELAYED_INVOICES_PROCESS_EVENT = 'DELAYED_INVOICES_PROCESS_EVENT',
    CALCULATE_INVOICE_BILLING = 'CALCULATE_INVOICE_BILLING',
}
