export enum CodeEnum {
    RECOVER_PASSWORD = 'RECOVER_PASSWORD',
    CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT',
    GUEST_CONFIRM_ACCOUNT = 'GUEST_CONFIRM_ACCOUNT',
    GUEST_LOGIN = 'GUEST_LOGIN',
    CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}

export enum AuthRedirectType {
    ADMIN_REDIRECT = 'ADMIN_REDIRECT',
    CLIENT_REDIRECT = 'CLIENT_REDIRECT',
}
