export enum FileType {
    HOST_INVOICE_PAYMENT = 'HOST_INVOICE_PAYMENT',
    HOST_PUBLIC_LOGO = 'HOST_PUBLIC_LOGO',
    HOST_PRODUCT_MEDIA = 'HOST_PRODUCT_MEDIA',
    HOST_PRODUCT_TESTIMONIALS = 'HOST_PRODUCT_TESTIMONIALS',
    HOST_PRODUCT_CONTENTS = 'HOST_PRODUCT_CONTENTS',
    HOST_PRODUCT_CONTENTS_THUMBNAILS = 'HOST_PRODUCT_CONTENTS_THUMBNAILS',
}
