export enum Frequency {
    MONTHLY = 'MONTHLY',
    WEEKLY = 'WEEKLY',
    EVERY_TWO_WEEKS = 'EVERY_TWO_WEEKS',
    EVERY_THREE_WEEKS = 'EVERY_THREE_WEEKS',
    BIWEEKLY = 'BIWEEKLY',
    EVERY_TWO_MONTHS = 'EVERY_TWO_MONTHS',
    QUARTERLY = 'QUARTERLY',
    ANNUALLY = 'ANNUALLY',
}
