export enum KYCStatus {
    NOT_STARTED = 'NOT_STARTED',
    APPROVED = 'APPROVED',
    DECLINED = 'DECLINED',
    IN_REVIEW = 'IN_REVIEW',
    ABANDONED = 'ABANDONED',
    MAX_RETRIES_REACHED = 'MAX_RETRIES_REACHED',
}
