export enum ProductStepType {
    TEXT = 'TEXT',
    FORM = 'FORM',
    WHATSAPP_GROUP = 'WHATSAPP_GROUP',
    TELEGRAM_CHANNEL = 'TELEGRAM_CHANNEL',
    DISCORD_CHANNEL = 'DISCORD_CHANNEL',
    ZOOM = 'ZOOM',
    GOOGLE_MEETS = 'GOOGLE_MEETS',
    MICROSOFT_TEAMS = 'MICROSOFT_TEAMS',
    LINK = 'LINK',
    CUSTOM = 'CUSTOM',
    MEETING_INVITATION = 'MEETING_INVITATION',
}
