export enum TelegramTemplate {
    USER_CREATED = 'USER_CREATED',
    PRODUCT_CREATED = 'PRODUCT_CREATED',
    PRODUCT_DUPLICATED = 'PRODUCT_DUPLICATED',
    BOOKING_CREATED = 'BOOKING_CREATED',
    PRODUCT_PUBLISHED = 'PRODUCT_PUBLISHED',
    INVOICE_PAYMENT_CREATED = 'INVOICE_PAYMENT_CREATED',
}
